#!/bin/bash

arg=${1}

log() {
    echo "$@" >&2
}

command -v atgo && { current=$(atgo version 2>&1) || exit 1 ; }
log "Current version : $current"

if [ "$arg" != "-f" ] ; then
    latest=$(curl -s https://api.github.com/repos/meian/atgo/releases/latest | grep tag_name | cut -d'"' -f4)
    log "Latest version  : $latest"
    if [ "$current" = "$latest" ] ; then
        log "Already up-to-date"
        exit 0
    fi
fi

curl -sSfL https://raw.githubusercontent.com/meian/atgo/main/install | bash
